### ISSUE TITLE
I get this error when I try to build

### ISSUE THREAD

**Issue by CheyenneForbes** [Azure/hdinsight-phoenix-sharp#10]
PhoenixSharp\PhoenixClient.cs(64,38): Error CS1061: 'PrepareAndExecuteRequest' does not contain a definition for 'ToByteString' and no extension method 'ToByteString' accepting a first argument of type 'PrepareAndExecuteRequest' could be found (are you missing a using directive or an assembly reference?)

**Comment by onpduo** [comment]
@CheyenneForbes 

The project has a nuget dependency of Google.Protobuf 3.0.0-alpha4. Visual Studio 2015 and Xamarin Studio built successfully as I just tested.

**Comment by CheyenneForbes** [comment]
I am using visual studio online.... visualstudio.com

**Comment by onpduo** [comment]
@CheyenneForbes 

Not tried that one. The error is due to you do not have Google.Protobuf nuget package installed (does VSO support nuget?). After you install it, you should not see this error.

**Comment by CheyenneForbes** [comment]
yes, it said "Added package 'Google.Protobuf.3.0.0-alpha4' to folder 'C:\a\1\s\packages'" and I tried from ShardDevelop (I am not able to use VS, I'm using windows 7) and I got this error and more:

Non-invocable member 'Google.Protobuf.Reflection.FileDescriptor.DescriptorProtoFileDescriptor' cannot be used like a method. (CS1955) - C:\Users\{User}\Downloads\hdinsight-phoenix-sharp-master\Apache.Phoenix\Common.cs:106,39

**Comment by onpduo** [comment]
@CheyenneForbes 

I suspect it is ShardDevelop specific issue or some nuget package not loaded successfully. Common.cs was auto generated by Google Protobuf protoc.exe. The same project was loaded successfully by VS2015 and Xamarin Studio on Mac.

If VS is not an option for you, I would suggest you to try Xamarin Studio, which is a cross-platform and lightweight IDE.

**Comment by onpduo** [comment]
Sorry, it should be MonoDevelop, but now it is bundled with Xamarin Studio.
http://www.monodevelop.com/download/

**Comment by CheyenneForbes** [comment]
I got it to build using VS on an Azure VM

I added this to see the output of the select query in ManyRowInsertTest() in PhoenixClientTests:

long count = executeResponse.Results[0].FirstFrame.Rows[0].Value[0].Value[0].NumberValue;
Debug.WriteLine(count);

what should I do after i build it to see the output?

**Comment by duoxu** [comment]
@CheyenneForbes 

That means you are good to go. I do not understand your questions. Did any test fail?

**Comment by CheyenneForbes** [comment]
I would like to see the wire message of the prepared statement in the console, I am using this C# client to troubleshoot a python client I am developing. So i'd like to compare both wire messages of the prepared statement to see where I went wrong with my python client

**Comment by duoxu** [comment]
@CheyenneForbes 

I see. You can set break points in VS and run tests in debug mode to see each variable's values like wiremessage object, but for the real wire message sent out, you may need to use fiddler or other tools to catch the packets and compare while running the code.

**Comment by CheyenneForbes** [comment]
I am trying on .NET Fiddle but I am getting this error "The name 'ClusterCredentialsFactory' does not exist in the current context"

Fiddle: https://dotnetfiddle.net/nmHWFB

**Comment by CheyenneForbes** [comment]
I got it fixed by changing 
`_credentials = ClusterCredentialsFactory.CreateFromFile(@"credentials.txt")`
to
`_credentials = new ClusterCredentials(new Uri("https://cluster"),"user","passwrd")`

 but now I am getting this

System.AggregateException: One or more errors occurred. ---> System.TypeLoadException: Could not load type 'Google.Protobuf.Preconditions' from assembly 'Google.Protobuf, Version=3.0.0.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'.
   at Apache.Phoenix.OpenConnectionRequest.set_ConnectionId(String value)
   at PhoenixSharp.PhoenixClient.<OpenConnectionRequestAsync>d__a.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at PhoenixSharp.UnitTests.PhoenixClientTests.Main() in d:\Windows\Temp\2ezeu2dy.0.cs:line 46
---> (Inner Exception #0) System.TypeLoadException: Could not load type 'Google.Protobuf.Preconditions' from assembly 'Google.Protobuf, Version=3.0.0.0, Culture=neutral, PublicKeyToken=a7d26565bac4d604'.
   at Apache.Phoenix.OpenConnectionRequest.set_ConnectionId(String value)
   at PhoenixSharp.PhoenixClient.<OpenConnectionRequestAsync>d__a.MoveNext()<---

**Comment by duoxu** [comment]
@CheyenneForbes 
Never see this before, did you load the Google.Protobuf version correctly? The version comes with this SDK is  3.0.0-alpha4. I am not sure if the later version will work properly. I will update to the latest Google.Protobuf version.

**Comment by duoxu** [comment]
The latest version has upgraded to Google.Protobuf 3.0.0. i think you should be good now.
