### ISSUE TITLE
Upgrade to Google.Protobuf 3.0.0 (non alpha/beta)

### ISSUE THREAD

**Issue by dwdii** [Azure/hdinsight-phoenix-sharp#11]
Google recently (Aug 11) released their Google.Protobuf package out of beta:

[https://www.nuget.org/packages/Google.Protobuf/3.0.0](https://www.nuget.org/packages/Google.Protobuf/3.0.0)

It would be great to move Microsoft.Phoenix.Client up to this version and work through any issues so MPC can be released out of preview!

Best Regards,

Daniel

**Comment by duoxu** [comment]
Will do.

**Comment by duoxu** [comment]
Committed.

**Comment by dwdii** [comment]
@duoxu Thanks! Would you be able to share when this might get published to nuget?

**Comment by duoxu** [comment]
The earliest would be by the end of this month.

**Comment by dwdii** [comment]
Thanks @duoxu. Fair enough.... I'll keep my eye out for it.
