### ISSUE TITLE
select counts doesn't work on my environment

### ISSUE THREAD

**Issue by pablocastilla** [Azure/hdinsight-phoenix-sharp#14]
Hi!

When I execute the tests (f.e. SimpleTest) it fails in the select count(*) with: 
Exception thrown: 'System.ArgumentOutOfRangeException' in Google.Protobuf.dll

The response is:
+		execResponse3	{{ "results": [ { "connectionId": "df5b8c40", "statementId": 56, "ownStatement": true, "signature": { "columns": [ { "caseSensitive": true, "searchable": true, "signed": true, "displaySize": 40, "label": "COUNT(1)", "columnName": "COUNT(1)", "tableName": "PERSONSDF5B8C40", "readOnly": true, "columnClassName": "java.lang.Long", "type": { "id": 4294967291, "name": "BIGINT", "rep": "PRIMITIVE_LONG" } } ], "cursorFactory": { "style": "LIST" } }, "firstFrame": { "done": true }, "updateCount": "18446744073709551615", "metadata": { "serverAddress": "wn0-pcvtes:8765" } } ], "metadata": { "serverAddress": "wn0-pcvtes:8765" } }}	Apache.Phoenix.ExecuteResponse

The firstFrame doesn't have any number so it breaks.

I am using Azure, HDI 3.4.1.

Any ideas?

Thanks

**Comment by pablocastilla** [comment]
ok, it works under HDI 3.5. Must be somethign about phoenix version.

**Comment by duoxu** [comment]
@pablocastilla 

Please see the README.md, the current source code which targets version 2.0 in nuget is only compatible with HDI 3.5 PQS and later versions.

If you are using HDI 3.4, you can download version 1.x in nuget.org.

Phoenix Query server GA in HDI 3.5 and have a lot of bug fixes, I would recommend you using the latest version in HDI.

Thanks,
Duo
