### ISSUE TITLE
Unable to run VNetTests.cs with Hortonworks Data Platform (2.3 and 2.4)

### ISSUE THREAD

**Issue by muralidharand** [Azure/hdinsight-phoenix-sharp#2]
First of all, thanks for your effort.
I'm able to connect Azure PQS from the unit testing code and it is working fine. 
I would like to use, VNetTests.cs unit testing code by connecting my local HDP ( Hortonworks Data Platform version 2.3 and 2.4) virtualbox images, but both the versions are failed with 404 error.
In both the versions(2.3 & 2.4), I've installed and configured Phoenix Query Server and I'm able to connect them via sqlline.py(JDBC) and it is working fine.
When I tried from .net based unit testing, I'm getting 404 error.
Can you please let me know, do I need to do any additional setup in the HDP to query it from .net application?

Thanks in advance.

**Comment by duoxu** [comment]
@muralidharand 
Is your phoenix query server reachable through "http://<PQS node ip>:8765"? Make sure the port number is 8765 and phoenix.queryserver.serialization = PROTOBUF

HDP 2.3's phoenix does not support Protobuf, only JSON. You need to confirm your HDP 2.4 Phoenix Query Server supports PROTOBUF.

**Comment by muralidharand** [comment]
I'm able to run the unit test(vntests.cs) after configuring phoenix.queryserver.serialization = PROTOBUF in HDP 2.4 . 
I blogged the steps the beginners also here http://www.codingfreaks.net/2017/01/getting-started-with-microsoft-net.html
