### ISSUE TITLE
 VNetTests.cs unit testing is failing with Hortonworks Data Platform (2.3 & 2.4) Linux VM

### ISSUE THREAD

**Issue by muralidharand** [Azure/hdinsight-phoenix-sharp#3]
First of all, thanks for your effort.
I'm able to connect Azure PQS from the unit testing code and it is working fine. 
I would like to use, VNetTests.cs unit testing code by connecting my local HDP ( Hortonworks Data Platform version 2.3 and 2.4) virtualbox images, but both the versions are failed with 404 error.
In both the versions(2.3 & 2.4), I've installed and configured Phoenix Query Server and I'm able to connect them via sqlline.py(JDBC) and it is working fine.
When I tried from .net based unit testing, I'm getting 404 error.
Can you please let me know, do I need to do any additional setup in the HDP to query it from .net application?

Thanks in advance.

**Comment by duoxu** [comment]
duplicate issue of #2 , close
