### ISSUE TITLE
Prepare then Execute Missing Results (No Mapping to Phoenix DECIMAL)

### ISSUE THREAD

**Issue by brycehodson** [Azure/hdinsight-phoenix-sharp#6]
Please let me know if there's somewhere else this should go.

PrepareAndExecute works just fine for me; I can get my desired output (insecurely) like this:
```
ExecuteResponse execResponse = client.PrepareAndExecuteRequestAsync(connId, cmdTextPAE, ulong.MaxValue, createStatementResponse.StatementId, options).Result;
foreach (var res in execResponse.Results[0].FirstFrame.Rows)
    Console.WriteLine(res.Value[0].Value[0].StringValue + " | " + res.Value[1].Value[0].NumberValue);
```

but when I use Prepare and then Execute like so:
```
PrepareResponse prepareResponse = client.PrepareRequestAsync(connId, cmdTextPTE, ulong.MaxValue, options).Result;
StatementHandle statementHandle = prepareResponse.Statement;	
ExecuteResponse executeResponse = client.ExecuteRequestAsync(statementHandle, paramList, ulong.MaxValue, true, options).Result;
Console.WriteLine(executeResponse.Results[0].FirstFrame);
FetchResponse fetchResponse = client.FetchRequestAsync(connId, createStatementResponse.StatementId, 0, uint.MaxValue, options).Result;
Console.WriteLine(fetchResponse);
```
the output is
```
{ "done": true }
{ "missingResults": true, "metadata": { "serverAddress": "hostserver:8765" } }
```
(and from further investigation I can say the other information in the executeResponse all looks correct, but none of it is actually the result set)

Just by looking at the unit tests I can't see that I'm using anything wrong, but obviously that's the less-likely possibility. If I really am not though, then there seems to be a problem with the Prepare-then-Execute system, as it's missing a result set that PrepareAndExecute is finding just fine.

**Comment by duoxu** [comment]
@brycehodson 

Could you provide a repro? What table schema do you have and what queries are you executing?

I can quickly help you debug your code if you can provide a repro.

Thanks,
Duo

**Comment by brycehodson** [comment]
@duoxu 

Create statement:
CREATE TABLE ShippingFact (
DataId DECIMAL(18,0),
IsCurrent BOOLEAN NOT NULL,
NumericData DECIMAL(18,2),
ShippingKey BIGINT NOT NULL,
CustomerId VARCHAR,
StringData VARCHAR,
DateData TIMESTAMP,
StartDate TIMESTAMP,
EndDate TIMESTAMP,
CONSTRAINT my_pk PRIMARY KEY(DataId, IsCurrent, NumericData, ShippingKey)
) SALT_BUCKETS=32;

Query:
SELECT CustomerId, StartDate, EndDate from ShippingFact fact0 where (fact0.StartDate < to_date('2016-06-06') OR fact0.StartDate IS NULL) AND (fact0.EndDate >= to_date('2015-12-05') OR fact0.EndDate IS NULL) AND fact0.IsCurrent = true AND (fact0.NumericData >= ? AND fact0.NumericData < ?) AND fact0.DataId = 20

Parameters: 39.11, 40.02
(both with Type = Rep.FLOAT. Maybe this is my error, though using Rep.BIG_DECIMAL results in "While parsing a protocol message, the input ended unexpectedly in the middle of a field..." and Rep.PRIMITIVE_FLOAT results in "...cannot convert 0.0 (class java.lang.Float) to PRIMITIVE_FLOAT...")

Example Results:
'M123456'	2016-02-18 16:00:00	2016-02-18 16:00:00
'M123456'	2016-02-18 16:00:00	2016-02-18 16:00:00
'M115432'	2016-01-11 00:00:00	2016-01-11 00:00:00
'M123456'	2016-02-18 00:00:00	2016-02-18 00:00:00
'M123456'	2016-02-18 16:00:00	2016-02-18 16:00:00

Let me know if there's anything it would be helpful to know that I've missed. Thanks a lot for your help!

**Comment by duoxu** [comment]
@brycehodson 
I tested and had the same issue. The problem is that there is no correct type in Rep mapping to Phoenix DECIMAL, which I think is a bug in Avatica/Phoenix Query Server. I have contacted Hortonworks regarding this. They will take a look and hopefully come out a fix soon.

For now, you can either use DOUBLE in your schema, and in your execute request,

                TypedValue v1 = new TypedValue
                {
 
                    DoubleValue = 39.11,
                    Type = Rep.DOUBLE
                };
                TypedValue v2 = new TypedValue
                {
                    DoubleValue = 40.02,
                    Type = Rep.DOUBLE
                };

Or you can use PrepareAndExecute to avoid specifying the value type.

**Comment by brycehodson** [comment]
@duoxu 
Ok, thanks a ton! We'll move to double for now and I'll keep watching for that possible fix.

**Comment by duoxu** [comment]
@brycehodson 
I will keep this open until we have a fix in our cluster offering.

**Comment by brycehodson** [comment]
@duoxu 
UPDATE:
It seems this isn't actually unique to datatype- after some experimentation, we've found that we can replicate this after changing to doubles, and also with date parameters. I'll try to add some code to this comment tomorrow, but the only difference is where in our command text there are ? vs filled-in parameters, and what properties the TypedValue is declared with.

**Comment by duoxu** [comment]
@brycehodson 

The latest HDI 3.5 (HDP 2.5, Phoenix 4.7, Avatica 1.8.0) fixed this issue. A new version of nuget package will be published soon.

pbc::RepeatedField<TypedValue> list = new pbc.RepeatedField<TypedValue>();
                TypedValue v1 = new TypedValue
                {
                    StringValue = "39.11",
                    Type = Rep.BigDecimal
                };
                TypedValue v2 = new TypedValue
                {
                    StringValue = "40.02",
                    Type = Rep.BigDecimal
                };
